export const categorySlugMap: Record<string, string> = {
  "beauty": "Beauty",
  "fragances": "Fragrances",
  "furniture": "Furniture",
  "groceries": "Groceries",
  "home-decoration": "Home Decoration",
  "kitchen-accesories": "Kitchen Accessories",
  "laptops": "Laptops",
  "mens-shirts": "Mens Shirts",
  "mens-shoes": "Mens Shoes",
  "mens-watches": "Mens Watches",
  "mobile-accesories": "Mobile Accessories",
  "motorcycle": "Motorcycle",
  "skin-care": "Skin Care",
  "smartphones": "Smartphones",
  "sports-accessories": "Sports Accessories",
  "sunglasses": "Sunglasses",
  "tablets": "Tablets",
  "tops": "Tops",
  "vehicle": "Vehicle",
  "womens-bags": "Womens Bags",
  "womens-dresses": "Womens Dresses",
  "womens-jewerlly": "Womens Jewellery",
  "womens-shoes": "Womens Shoes",
  "womens-watches": "Womens Watches",
};
